// Drills WebAssembly Demo Application

class DrillsDemo {
    constructor() {
        this.engine = null;
        this.isLoaded = false;
        this.loadStartTime = 0;

        this.initializeUI();
        this.bindEvents();

        // Show loading modal
        this.showLoadingModal();

        // Start loading WebAssembly
        this.loadWebAssembly();
    }

    initializeUI() {
        this.elements = {
            // Buttons
            initBtn: document.getElementById('init-btn'),
            createKbBtn: document.getElementById('create-kb-btn'),
            createSessionBtn: document.getElementById('create-session-btn'),
            loadSampleBtn: document.getElementById('load-sample-btn'),
            insertFactBtn: document.getElementById('insert-fact-btn'),
            fireRulesBtn: document.getElementById('fire-rules-btn'),
            queryBtn: document.getElementById('query-btn'),
            executeCustomBtn: document.getElementById('execute-custom-btn'),
            clearConsoleBtn: document.getElementById('clear-console-btn'),

            // Inputs
            customFactInput: document.getElementById('custom-fact'),
            customQueryInput: document.getElementById('custom-query'),

            // Outputs
            consoleOutput: document.getElementById('console-output'),
            statusIndicator: document.getElementById('status-indicator'),
            statusText: document.getElementById('status-text'),
            resultsPanel: document.getElementById('results-panel'),
            resultsJson: document.getElementById('results-json'),

            // Status
            statusInitialized: document.getElementById('status-initialized'),
            statusKb: document.getElementById('status-kb'),
            statusSession: document.getElementById('status-session'),
            statusWasm: document.getElementById('status-wasm'),

            // Performance
            loadTime: document.getElementById('load-time'),
            memoryUsage: document.getElementById('memory-usage'),

            // Modals
            loadingModal: document.getElementById('loading-modal')
        };
    }

    bindEvents() {
        // Engine lifecycle
        this.elements.initBtn.addEventListener('click', () => this.initializeEngine());
        this.elements.createKbBtn.addEventListener('click', () => this.createKnowledgeBase());
        this.elements.createSessionBtn.addEventListener('click', () => this.createSession());

        // Operations
        this.elements.loadSampleBtn.addEventListener('click', () => this.loadSampleData());
        this.elements.insertFactBtn.addEventListener('click', () => this.insertSampleFact());
        this.elements.fireRulesBtn.addEventListener('click', () => this.fireRules());
        this.elements.queryBtn.addEventListener('click', () => this.executeSampleQuery());

        // Custom operations
        this.elements.executeCustomBtn.addEventListener('click', () => this.executeCustomOperation());

        // Utility
        this.elements.clearConsoleBtn.addEventListener('click', () => this.clearConsole());

        // Keyboard shortcuts
        document.addEventListener('keydown', (e) => {
            if (e.ctrlKey && e.key === 'Enter') {
                this.autoRunDemo();
            }
        });
    }

    async loadWebAssembly() {
        const startTime = performance.now();
        this.loadStartTime = startTime;

        try {
            this.log('info', '🔄 Loading Drills WebAssembly module...');

            // Load the WebAssembly module generated by Emscripten
            const response = await fetch('./drills.js');
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}: ${response.statusText}`);
            }

            const scriptText = await response.text();
            const script = document.createElement('script');
            script.textContent = scriptText;
            document.head.appendChild(script);

            // Wait for the module to be available
            await this.waitForModule();

            this.isLoaded = true;
            const loadTime = Math.round(performance.now() - startTime);

            this.log('success', `✅ WebAssembly loaded in ${loadTime}ms`);
            this.updateStatus('wasm', true);
            this.elements.loadTime.textContent = loadTime;

            // Update memory usage
            this.updateMemoryUsage();

        } catch (error) {
            this.log('error', `❌ Failed to load WebAssembly: ${error.message}`);
            this.log('info', '💡 Make sure the server is running and files are accessible');

            // Hide loading modal on error
            this.hideLoadingModal();
        }
    }

    waitForModule() {
        return new Promise((resolve, reject) => {
            const checkModule = () => {
                if (typeof window !== 'undefined' && window.DrillsEngine) {
                    resolve();
                } else {
                    setTimeout(checkModule, 100);
                }
            };

            checkModule();
        });
    }

    async initializeEngine() {
        if (!this.isLoaded) {
            this.log('error', '❌ WebAssembly not loaded yet. Please wait.');
            return;
        }

        try {
            this.showLoadingModal();
            this.log('info', '🚀 Initializing Drills engine...');

            // Create engine instance
            this.engine = new window.DrillsEngine();

            // Initialize
            const result = this.engine.init();

            if (result.includes('successfully')) {
                this.log('success', `✅ Engine initialized: ${result}`);
                this.updateStatus('initialized', true);
                this.enableButton(this.elements.createKbBtn);

                // Update UI to show engine is online
                this.updateEngineStatus(true);

                // Start memory monitoring
                this.startMemoryMonitoring();

            } else {
                this.log('error', `❌ Initialization failed: ${result}`);
            }

        } catch (error) {
            this.log('error', `❌ Error initializing engine: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async createKnowledgeBase() {
        if (!this.engine) {
            this.log('error', '❌ Engine not initialized');
            return;
        }

        try {
            this.showLoadingModal();
            this.log('info', '📚 Creating knowledge base...');

            const result = this.engine.createKnowledgeBase('');

            this.log('success', `✅ Knowledge base created: ${result}`);
            this.updateStatus('kb', true);
            this.enableButton(this.elements.createSessionBtn);

        } catch (error) {
            this.log('error', `❌ Error creating knowledge base: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async createSession() {
        if (!this.engine) {
            this.log('error', '❌ Engine not initialized');
            return;
        }

        try {
            this.showLoadingModal();
            this.log('info', '🎯 Creating session...');

            const result = this.engine.createSession();

            this.log('success', `✅ Session created: ${result}`);
            this.updateStatus('session', true);

            // Enable operation buttons
            this.enableButton(this.elements.loadSampleBtn);
            this.enableButton(this.elements.insertFactBtn);
            this.enableButton(this.elements.fireRulesBtn);
            this.enableButton(this.elements.queryBtn);
            this.enableButton(this.elements.executeCustomBtn);

        } catch (error) {
            this.log('error', `❌ Error creating session: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async loadSampleData() {
        if (!this.engine) {
            this.log('error', '❌ Engine not initialized');
            return;
        }

        try {
            this.showLoadingModal();
            this.log('info', '📋 Loading sample rules...');

            // Sample DRL rules
            const sampleRules = `
global java.util.List rulesFired;

rule "Customer Classification - VIP"
when
    $customer : Customer(age >= 30 && income > 100000)
then
    $customer.setCustomerType("VIP");
    rulesFired.add("VIP Customer Classification");
end

rule "Customer Classification - Regular"
when
    $customer : Customer(age >= 18 && income <= 100000)
then
    $customer.setCustomerType("Regular");
    rulesFired.add("Regular Customer Classification");
end

rule "Discount Calculation - VIP"
when
    $customer : Customer(customerType == "VIP")
then
    $customer.setDiscount(15.0);
    rulesFired.add("VIP Discount Applied");
end

rule "Discount Calculation - Regular"
when
    $customer : Customer(customerType == "Regular")
then
    $customer.setDiscount(5.0);
    rulesFired.add("Regular Discount Applied");
end
`;

            // Reload knowledge base with rules
            const result = this.engine.createKnowledgeBase(sampleRules);

            this.log('success', `✅ Sample rules loaded: ${result}`);
            this.log('info', '📝 Loaded 4 sample rules for customer classification and discounts');

        } catch (error) {
            this.log('error', `❌ Error loading sample data: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async insertSampleFact() {
        if (!this.engine) {
            this.log('error', '❌ Engine not initialized');
            return;
        }

        try {
            this.showLoadingModal();
            this.log('info', '➕ Inserting sample customer fact...');

            // Sample customer fact
            const customerFact = JSON.stringify({
                name: "Alice Johnson",
                age: 35,
                income: 120000,
                customerType: "",
                discount: 0.0
            });

            const result = this.engine.insertFact("Customer", customerFact);

            this.log('success', `✅ Customer fact inserted: ${result}`);
            this.log('info', '👤 Customer: Alice Johnson (35 years, $120k income)');

        } catch (error) {
            this.log('error', `❌ Error inserting fact: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async fireRules() {
        if (!this.engine) {
            this.log('error', '❌ Engine not initialized');
            return;
        }

        try {
            this.showLoadingModal();
            this.log('info', '🔥 Firing all rules...');

            const result = this.engine.fireRules();

            this.log('success', `✅ Rules fired: ${result}`);
            this.log('info', '🎯 Rules should have classified customer and applied discount');

        } catch (error) {
            this.log('error', `❌ Error firing rules: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async executeSampleQuery() {
        if (!this.engine) {
            this.log('error', '❌ Engine not initialized');
            return;
        }

        try {
            this.showLoadingModal();
            this.log('info', '🔍 Executing sample query...');

            // Sample query to find customers
            const queryResult = this.engine.query("findCustomers");

            if (queryResult.includes('results')) {
                this.displayQueryResults(queryResult);
                this.log('success', '✅ Query executed successfully');
                this.log('info', '📊 Results displayed below');
            } else {
                this.log('warning', `ℹ️ No results or query format issue: ${queryResult}`);
            }

        } catch (error) {
            this.log('error', `❌ Error executing query: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async executeCustomOperation() {
        const factJson = this.elements.customFactInput.value.trim();
        const queryName = this.elements.customQueryInput.value.trim();

        if (!factJson && !queryName) {
            this.log('warning', '⚠️ Please provide either a custom fact or query');
            return;
        }

        if (!this.engine) {
            this.log('error', '❌ Engine not initialized');
            return;
        }

        try {
            this.showLoadingModal();

            if (factJson) {
                this.log('info', `➕ Inserting custom fact: ${factJson}`);
                const result = this.engine.insertFact("Customer", factJson);
                this.log(result.includes('successfully') ? 'success' : 'error', result);
            }

            if (queryName) {
                this.log('info', `🔍 Executing custom query: ${queryName}`);
                const result = this.engine.query(queryName);
                this.displayQueryResults(result);
            }

        } catch (error) {
            this.log('error', `❌ Error in custom operation: ${error.message}`);
        } finally {
            this.hideLoadingModal();
        }
    }

    async autoRunDemo() {
        this.log('info', '🚀 Starting automatic demo sequence...');
        this.log('info', '💡 Press Ctrl+Enter at any time to run full demo');

        if (!this.isLoaded) {
            await this.loadWebAssembly();
        }

        if (!this.engine) {
            await this.initializeEngine();
        }

        await new Promise(resolve => setTimeout(resolve, 500));
        await this.createKnowledgeBase();

        await new Promise(resolve => setTimeout(resolve, 500));
        await this.createSession();

        await new Promise(resolve => setTimeout(resolve, 500));
        await this.loadSampleData();

        await new Promise(resolve => setTimeout(resolve, 500));
        await this.insertSampleFact();

        await new Promise(resolve => setTimeout(resolve, 500));
        await this.fireRules();

        await new Promise(resolve => setTimeout(resolve, 500));
        await this.executeSampleQuery();

        this.log('success', '🎉 Demo completed successfully!');
    }

    displayQueryResults(jsonResult) {
        this.elements.resultsJson.textContent = jsonResult;
        this.elements.resultsPanel.classList.remove('hidden');

        // Syntax highlight JSON using Prism
        if (window.Prism) {
            window.Prism.highlightElement(this.elements.resultsJson);
        }
    }

    log(level, message) {
        const timestamp = new Date().toLocaleTimeString();
        const logElement = document.createElement('div');

        switch (level) {
            case 'success':
                logElement.className = 'text-green-400';
                break;
            case 'error':
                logElement.className = 'text-red-400';
                break;
            case 'warning':
                logElement.className = 'text-yellow-400';
                break;
            case 'info':
            default:
                logElement.className = 'text-blue-400';
                break;
        }

        logElement.innerHTML = `<span class="text-gray-500">[${timestamp}]</span> ${message}`;

        this.elements.consoleOutput.appendChild(logElement);

        // Auto-scroll to bottom
        this.elements.consoleOutput.scrollTop = this.elements.consoleOutput.scrollHeight;

        // Limit console history
        while (this.elements.consoleOutput.children.length > 100) {
            this.elements.consoleOutput.removeChild(this.elements.consoleOutput.firstChild);
        }
    }

    clearConsole() {
        this.elements.consoleOutput.innerHTML = '';
        this.log('info', '🧹 Console cleared');
    }

    updateStatus(component, status) {
        const element = this.elements[`status${component.charAt(0).toUpperCase() + component.slice(1)}`];
        if (element) {
            element.className = status ? 'text-green-400' : 'text-red-400';
            element.textContent = status ? '✅ Yes' : '❌ No';
        }
    }

    updateEngineStatus(isOnline) {
        this.elements.statusIndicator.className = `w-3 h-3 rounded-full ${isOnline ? 'status-online' : 'status-offline'}`;
        this.elements.statusText.textContent = `Engine: ${isOnline ? 'Online' : 'Offline'}`;

        if (isOnline) {
            this.elements.statusIndicator.classList.add('pulse');
        } else {
            this.elements.statusIndicator.classList.remove('pulse');
        }
    }

    enableButton(button) {
        button.disabled = false;
        button.classList.remove('disabled:opacity-50', 'disabled:cursor-not-allowed');
    }

    showLoadingModal() {
        this.elements.loadingModal.classList.remove('hidden');
    }

    hideLoadingModal() {
        this.elements.loadingModal.classList.add('hidden');
    }

    updateMemoryUsage() {
        if ('memory' in performance) {
            const memInfo = performance.memory;
            const usedMB = Math.round(memInfo.usedJSHeapSize / 1024 / 1024);
            this.elements.memoryUsage.textContent = usedMB;
        } else {
            this.elements.memoryUsage.textContent = 'N/A';
        }
    }

    startMemoryMonitoring() {
        setInterval(() => this.updateMemoryUsage(), 1000);
    }
}

// Initialize the demo when the page loads
document.addEventListener('DOMContentLoaded', () => {
    window.drillsDemo = new DrillsDemo();
});

console.log('🎯 Drills WebAssembly Demo initialized');
console.log('💡 Press Ctrl+Enter for automatic demo');
console.log('🔧 Use browser dev tools for additional logging');
