ARG SALTS_SDK_IMAGE=salts-sdk:bookworm
ARG SALTS_UTILS_SDK_IMAGE=salts-utils-sdk:bookworm

FROM ${SALTS_UTILS_SDK_IMAGE} AS salts-utils-sdk
FROM ${SALTS_SDK_IMAGE}

ENV CMAKE_PREFIX_PATH=/opt/salts:/opt/salts-utils
ENV SALTS_ROOT=/opt/salts
ENV SALTS_UTILS_ROOT=/opt/salts-utils
ENV VCPKG_ROOT=/opt/vcpkg
ENV LD_LIBRARY_PATH=/opt/salts-utils/lib:/opt/salts/lib

WORKDIR /src/rulesforge

COPY vcpkg.json ./
RUN vcpkg install --triplet x64-linux

COPY --from=salts-utils-sdk /opt/salts-utils /opt/salts-utils
COPY . ./

RUN cmake -S . -B build -G Ninja \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_PREFIX_PATH=/opt/salts\;/opt/salts-utils \
    -D CMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake \
    -D VCPKG_TARGET_TRIPLET=x64-linux \
    -D BUILD_TESTING=OFF \
    -D ENABLE_TESTS=OFF \
    -D CMAKE_INSTALL_PREFIX=/opt/rulesforge \
    && cmake --build build \
    && cmake --install build
