ARG TURBONET_SDK_IMAGE=turbonet-sdk:bookworm
ARG TURBOSCRIPT_SDK_IMAGE=turboscript-sdk:bookworm

FROM ${TURBOSCRIPT_SDK_IMAGE} AS turboscript-sdk
FROM ${TURBONET_SDK_IMAGE}

ENV CMAKE_PREFIX_PATH=/opt/turbonet
ENV TURBONET_ROOT=/opt/turbonet
ENV TURBOSCRIPT_ROOT=/opt/turboscript
ENV VCPKG_ROOT=/opt/vcpkg
ENV LD_LIBRARY_PATH=/opt/turboscript/lib:/opt/turbonet/lib

WORKDIR /src/rulesforge

COPY vcpkg.json ./
RUN vcpkg install --triplet x64-linux

COPY --from=turboscript-sdk /opt/turboscript /opt/turboscript
COPY . ./

RUN cmake -S . -B build -G Ninja \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_PREFIX_PATH=/opt/turbonet\;/opt/turboscript \
    -D TURBONET_ROOT=/opt/turbonet \
    -D TURBOSCRIPT_ROOT=/opt/turboscript \
    -D CMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake \
    -D VCPKG_TARGET_TRIPLET=x64-linux \
    -D BUILD_TESTING=OFF \
    -D ENABLE_TESTS=OFF \
    -D CMAKE_INSTALL_PREFIX=/opt/rulesforge \
    && cmake --build build \
    && cmake --install build
