#ifndef DROOLS_PARSER_STATE_HPP
#define DROOLS_PARSER_STATE_HPP

#include "drools_rete_defs.hpp"

#include <memory>
#include <string>
#include <vector>

// This struct has been simplified to hold only the final results of parsing.
// The temporary state used by a previous action-based parser design has been removed.
// This makes the struct a simple, copyable data container for the AST.
struct parser_state {
    // Top-level metadata
    std::string package_name;
    std::vector<std::string> parsed_imports;

    // All successfully parsed top-level items
    std::vector<ParsedRule> parsed_rules;
    std::vector<ParsedQuery> parsed_queries;
    std::vector<ParsedFunction> parsed_functions;
    std::vector<ParsedDeclaration> parsed_declarations;
    std::vector<ParsedGlobal> parsed_globals;

    // The default copy constructor, copy assignment operator, move constructor,
    // move assignment operator, and destructor are all correctly generated by
    // the compiler for this simplified struct.
};

#endif   // DROOLS_PARSER_STATE_HPP


