set(CPR_ROOT ${EXTERNAL_ROOT}/cpr)
find_package(cpr PATHS ${CPR_ROOT})
set(LUA_ROOT ${EXTERNAL_ROOT}/lua)
find_package(Lua PATHS ${LUA_ROOT})
if(USE_OPENSSL)
    find_package(OpenSSL PATHS ${EXTERNAL_ROOT}/openssl)
endif()
set(BOOST_ROOT ${EXTERNAL_ROOT}/boost)
find_package(Boost REQUIRED)
set(OPENCV_ROOT ${EXTERNAL_ROOT}/opencv)
