# - Find Lemon Parser Generator executable and provides macros to generate custom build rules
# The module defines the following variables:
#
#  LEMON_EXECUTABLE - path to the lemon program
#  LEMON_FOUND - true if the program was found
#
# If lemon is found, the module defines the macros:
#
#  LEMON_TARGET(<Name> <LemonInp> <CodeOutput>
#               [COMPILE_FLAGS <string>])
#
# which will create a custom rule to generate a parser. <LemonInp> is
# the path to a Lemon grammar file. <CodeOutput> is the name of the source file
# generated by lemon. If COMPILE_FLAGS option is specified, the next
# parameter is added in the lemon command line.
#
# The macro defines a set of variables:
#  LEMON_${Name}_DEFINED       - true is the macro ran successfully
#  LEMON_${Name}_INPUT         - The input grammar file, an alias for <LemonInp>
#  LEMON_${Name}_OUTPUT_SOURCE - The source file generated by lemon
#  LEMON_${Name}_OUTPUT_HEADER - The header file generated by lemon
#  LEMON_${Name}_OUTPUTS       - The sources files generated by lemon
#  LEMON_${Name}_COMPILE_FLAGS - Options used in the lemon command line
#
#  ====================================================================
#  Example:
#
#   find_package(LEMON REQUIRED)
#   LEMON_TARGET(MyParser parser.y ${CMAKE_CURRENT_BINARY_DIR}/parser.c)
#   add_executable(Foo main.c ${LEMON_MyParser_OUTPUTS})
#  ====================================================================

find_program(LEMON_EXECUTABLE NAMES lemon DOC "path to the lemon executable")
mark_as_advanced(LEMON_EXECUTABLE)

if(LEMON_EXECUTABLE)
  # Lemon doesn't provide version information, so we'll just check if it exists
  set(LEMON_FOUND TRUE)

  #============================================================
  # LEMON_TARGET (public macro)
  #============================================================
  #
  macro(LEMON_TARGET Name Input Output)
    set(LEMON_TARGET_usage
        "LEMON_TARGET(<Name> <Input> <Output> [COMPILE_FLAGS <string>]"
    )
    if(${ARGC} GREATER 3)
      if(${ARGC} EQUAL 5)
        if("${ARGV3}" STREQUAL "COMPILE_FLAGS")
          set(LEMON_EXECUTABLE_opts "${ARGV4}")
          separate_arguments(LEMON_EXECUTABLE_opts)
        else()
          message(SEND_ERROR ${LEMON_TARGET_usage})
        endif()
      else()
        message(SEND_ERROR ${LEMON_TARGET_usage})
      endif()
    endif()

    get_filename_component(LEMON_INPUT_NAME ${Input} NAME_WE)
    get_filename_component(LEMON_INPUT_PATH ${Input} PATH)
    get_filename_component(LEMON_OUTPUT_PATH ${Output} PATH)
    get_filename_component(LEMON_OUTPUT_NAME ${Output} NAME_WE)
    set(LEMON_OUTPUT_HEADER "${LEMON_OUTPUT_PATH}/${LEMON_OUTPUT_NAME}.h")

    # Generate the output file at configure time
    execute_process(
      COMMAND
        ${LEMON_EXECUTABLE} ${LEMON_EXECUTABLE_opts}
        -T${PROJECT_SOURCE_DIR}/vendor/lemon/lempar.c -d${LEMON_OUTPUT_PATH}
        ${Input}
      WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
      RESULT_VARIABLE STATUS
      ERROR_QUIET
    )
    if(STATUS AND NOT STATUS EQUAL 0)
      message(STATUS "Lemon generation FAILED: ${STATUS}")
    else()
      message(STATUS "Lemon generation SUCCESS ")
      configure_file(
        ${LEMON_OUTPUT_PATH}/${LEMON_OUTPUT_NAME}.c ${Output} COPYONLY
      )
    endif()

    # Add a custom command to regenerate the output if the input changes
    add_custom_command(
      OUTPUT ${Output} ${LEMON_OUTPUT_HEADER}
      COMMAND ${CMAKE_COMMAND} -E remove -f
              ${LEMON_OUTPUT_PATH}/${LEMON_INPUT_NAME}.c
      COMMAND ${CMAKE_COMMAND} -E remove -f ${Output}
      COMMAND
        ${LEMON_EXECUTABLE} ARGS ${LEMON_EXECUTABLE_opts}
        -T${PROJECT_SOURCE_DIR}/vendor/lemon/lempar.c -d${LEMON_OUTPUT_PATH}
        ${Input}
      COMMAND ${CMAKE_COMMAND} -E rename ${LEMON_INPUT_NAME}.c ${Output}
      DEPENDS ${Input}
      COMMENT "[LEMON][${Name}] Generating parser with Lemon"
      WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    )
    set(LEMON_${Name}_DEFINED TRUE)
    set(LEMON_${Name}_OUTPUTS ${Output} ${LEMON_OUTPUT_HEADER})
    set(LEMON_${Name}_INPUT ${Input})
    set(LEMON_${Name}_OUTPUT_SOURCE ${Output})
    set(LEMON_${Name}_OUTPUT_HEADER ${LEMON_OUTPUT_HEADER})
    set(LEMON_${Name}_COMPILE_FLAGS ${LEMON_EXECUTABLE_opts})
  endmacro()

endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LEMON REQUIRED_VARS LEMON_EXECUTABLE)
