pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_NON_GA_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "MyAndroidDrillsApp"
include ':app'
